### PR TITLE
Fix Issue #344 by adding encode with utf-8

### PR DESCRIPTION
**Pull request by dkim0526**
##### Description
This PR is to fix the Issue #344 when updating changes in map entries. It was because of the `UnicodeDecodeError` on non-ascii values, and the fix was adding encoding with unicode format

- Add encoding with `utf-8` on `__str__` methods
- Remove trailing whitespaces

### CODE REVIEW

**Comment by indirectlylit** [comment]
great! Is this something we can run and reproduce locally to test the PR?

**Comment by dkim0526** [comment]
@indirectlylit Yes, I was able to reproduce the error in the current develop branch by following steps:
1. Go to http://127.0.0.1:8000/ka-lite/map/add/  and add a story with non ascii code like `CREE - Instituto Héctor Orlando Gómez Cisneros`
2. Use the local environment and go to `http://127.0.0.1:8000/admin/ka_lite/deploymentstory/` and click the deployment story that was created in the previous step
3. Then there should be an error like:

 ```bash
  'ascii' codec can't encode character \xe9 in position 46: ordinal not in range(128) 

 ```


I think if database already contains deployment stories with special characters, just by going to `http://127.0.0.1:8000/admin/ka_lite/deploymentstory/add/` would give the error as well.

After applying this change, the error was gone and I was able to see the deployment stories with special characters. Please let me know if you have any suggestions or questions.

**Comment by indirectlylit** [comment]
interesting, I can't reproduce the original issue

| image | image |
|--|--|

However, let's give it a go!

**Comment by jeepurs** [comment]
Tested this in two ways:
1. Creating a new map entry. Was able to do so (nb: I just populated every field with 'test' text which isn't necessarily robust).
2. Clicked a previously submitted map entry to edit and publish, and was able to do so

So looks good to me!  (CC @lauradanforth )

**Comment by lauradanforth** [comment]
@jeepurs hmm I'm still getting the 500 error when clicking to edit an entry. See [#344](https://github.com/learningequality/learningequality.org/issues/344#issuecomment-388587933)

**Pull request merged**
