### PR TITLE
download page tweaks

### PR DESCRIPTION
**Pull request by indirectlylit**
before:

image

after:

image

### CODE REVIEW

**Comment by jamalex** [comment]
I think what I was starting to type in there was a recommendation to use pip for online updates. But we can iterate on this further after.

**Comment by benjaoming** [comment]
I think it looks like the buttons suggest their way of doing it, and then the text below contradicts it. Could there be two buttons and then we use asterisks to denote details?

37608224-3bf972f0-2b57-11e8

**Comment by benjaoming** [comment]
The icons are badly chosen, but basically: Use a download icon to symbolize the "portable" option and a subscription icon to symbolize PyPi, PPA... and maybe some day homebrew.

**Comment by khangmach** [comment]
I think the download options looked totally fine without the new icons in buttons. Let's just keep it simple for now and remove those in-line icons. I don't think users particularly really mind the special special special difference between "download" and" install"...end of the day it's going to be "downloaded to their device anyways...

**Comment by benjaoming** [comment]
@khangmach there are no icons in @indirectlylit -- I photoshopped this part as a suggestion because the "download" word is long and blurs the meaning of portable vs. "subscribable".

**Comment by benjaoming** [comment]
> .end of the day it's going to be "downloaded to their device anyways...

@khangmach I disagree... it's why I wrote an elaborated description in #382

**Comment by indirectlylit** [comment]
@benjaoming those are fair points, but I don't think they should block merging of this PR. Can we get this in and continue to iterate?

**Comment by indirectlylit** [comment]
(note from my description at the top that this was a small iteration on previous work)

**Comment by indirectlylit** [comment]
thanks. for what it's worth, I agree with this:

> I think it looks like the buttons suggest their way of doing it, and then the text below contradicts it. Could there be two buttons and then we use asterisks to denote details?

**Pull request merged**
